language: generic
sudo: required  
services:
  - docker

before_install:
  - docker build -t archit2406/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true archit2406/react-test npm test

after_success:
  - docker build -t archit2406/multi-client ./client
  - docker build -t archit2406/multi-nginx ./nginx
  - docker build -t archit2406/multi-server ./server
  - docker build -t archit2406/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push archit2406/multi-client
  - docker push archit2406/multi-nginx
  - docker push archit2406/multi-server
  - docker push archit2406/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: elasticbeanstalk-us-east-2-456437408769
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
